---
# tasks file for docker-buildkit

- name: check for {{ bk_install_dir }}
  become: yes
  stat:
    path: '{{ bk_install_dir }}'
  changed_when: False
  register: install_dir
- when: not install_dir.stat.exists
  block:
    - debug:
        msg:
          - bk_arch: '{{ bk_arch }}'
            bk_file_name: '{{ bk_file_name }}'
            bk_tar: '{{ bk_tar }}'
            bk_sbom: '{{ bk_sbom }}'
            bk_sbom_url: '{{ bk_sbom_url }}'
    - name: fetch sbom from {{ bk_sbom_url }}
      uri: 
        url: '{{ bk_sbom_url }}'
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
        timeout: '{{ bk_timeout_seconds }}'
      register: sbom_res
    - set_fact:
        sbom: '{{ sbom_res.content | from_json }}'
    - set_fact:
        checksum: 'sha256:{{ sbom.subject[0].digest.sha256 }}'
    - name: download {{ bk_url }}/{{ bk_tar }}
      get_url:
        url: '{{ bk_url }}/{{ bk_tar }}'
        dest: '{{ bk_install_dir }}/{{ bk_tar }}'
        checksum: '{{ checksum }}'
        timeout: '{{ bk_timeout_seconds }}'
        mode: 0644

    # - name: download {{ abc_url }}...
    #   become: yes
    #   become_user: root
    #   get_url:
    #     url: '{{ abc_url }}'
    #     dest: '{{ abc_tmp_tgz }}'
    #     checksum: '{{ abc_checksum }}'
    #     mode: 0644
    # - name: mkdir {{ abc_install_dir }}
    #   become: yes
    #   become_user: root
    #   file:
    #     path: '{{ abc_install_dir }}'
    #     state: directory
    #     mode: 0755
    # - name: unarchive {{ abc_tmp_tgz }}
    #   become: yes
    #   become_user: root
    #   unarchive:
    #     remote_src: yes
    #     src: '{{ abc_tmp_tgz }}'
    #     dest: '{{ abc_install_dir }}'
    #     creates: '{{ abc_installed_exe }}'
  # always:
  #   - name: rm {{ abc_tmp_tgz }}
  #     become: yes
  #     become_user: root
  #     file:
  #       path: '{{ abc_tmp_tgz }}'
  #       state: absent
# - name: link {{ abc_installed_link }} to {{ abc_installed_exe }}
#   become: yes
#   become_user: root
#   file:
#     src: '{{ abc_installed_exe }}'
#     dest: '{{ abc_installed_link }}'
#     state: link
